### ISSUE TITLE
Document how to use ko with kind

### ISSUE THREAD

**Issue by jonjohnsonjr** [google/ko#123]
Feedback from tgik.io/102 that we should explain how to use `ko` with [kind](https://github.com/kubernetes-sigs/kind).

**Comment by marcindulak** [comment]
This may be possible by configuring https://kind.sigs.k8s.io/docs/user/local-registry/, but ...

- enable https://docs.docker.com/registry/insecure/ docker registry, e.g. on Debian/Ubuntu

  ```sh
  sudo sed -i 's/127\.0\.0\.1.*$/& registry/' /etc/hosts
  sudo sh -c 'echo "{ \"insecure-registries\" : [ \"registry:5000\" ] }" > /etc/docker/daemon.json'
  sudo systemctl restart docker
  sudo systemctl status docker
  ```

- start a single node kind (0.7.0) k8s cluster (1.17.0) alongside with a local docker registry in a container

   ```sh
   curl -sLO https://github.com/kubernetes-sigs/kind/raw/master/site/static/examples/kind-with-registry.sh
   bash kind-with-registry.sh
   ```

   ```sh
   docker ps --format '{{.Names}}'
   kind-control-plane
   kind-registry
   ```

- test the registry as described at https://kind.sigs.k8s.io/docs/user/local-registry/ by creating a deployment

  ```sh
  docker pull gcr.io/google-samples/hello-app:1.0
  docker tag gcr.io/google-samples/hello-app:1.0 registry:5000/hello-app:1.0
  docker push registry:5000/hello-app:1.0
  kubectl create deployment hello-server --image=registry:5000/hello-app:1.0
  ```

- deploy a test pod with ko

  ```
  go get github.com/google/ko/cmd/ko/test
  curl -sLO https://raw.githubusercontent.com/google/ko/master/cmd/ko/test/test.yaml
  cat test.yaml
  apiVersion: v1
  kind: Pod
  metadata:
    name: kodata
    annotations:
      sidecar.istio.io/inject: "false"
  spec:
    containers:
    - name: obiwan
      image: github.com/google/ko/cmd/ko/test
    restartPolicy: Never
  ```

  but (with https://github.com/google/ko/commit/99ecfeb5c41dca4f808e8f22184717bda505cddd) ...
  ```
  KO_DOCKER_REPO=registry:5000 ko apply -f test.yaml
  2020/01/24 23:57:20 No matching credentials were found, falling back on anonymous
  2020/01/24 23:57:20 Using base gcr.io/distroless/static:latest for github.com/google/ko/cmd/ko/test
  2020/01/24 23:57:21 Building github.com/google/ko/cmd/ko/test
  2020/01/24 23:57:21 Publishing registry:5000/test-0e3a563dcfe31cd0109fe43c1bf7c91e:latest
  2020/01/24 23:57:21 error processing import paths in "test.yaml": error resolving image references: 
  Get https://registry:5000/v2/: http: server gave HTTP response to HTTPS client
  error: no objects passed to apply
  ```
