### ISSUE TITLE
Question / suggestion about conditional compilations.

### ISSUE THREAD

**Issue by vaikas** [google/ko#513]
I saw that you can specify multiple entries in the .ko.yaml file, and then there's some magic that happens as per:

```
ko picks the entry from builds based on the import path you request. The import path is matched against the result of joining dir and main.
```

My question is on the best way to handle something like this (where I do want to build same binary with different flags):
```
defaultBaseImage: gcr.io/distroless/base-debian10
builds:
- id: default 
  main: .
  env:
  - CGO_ENABLED=1
# If you are deploying from M1, you can use this (uncomment this, and
# comment above), though it does remove the support for the "createca" command.
# But at least you can deploy it from M1 using this.
#- id: purego 
#  main: .
#  flags:
#  - -tags=purego
```

I played around a bit and couldn't figure out a better solution than documentation. If this could be documented on the trickery that I could use here, or the suggestion would be to be able to specify when executing `ko` which ID should be used.

**Comment by imjasonh** [comment]
This config format is largely adopted from [goreleaser](https://goreleaser.io), which AFAIK doesn't have such a concept of conditional config or profiles. I wouldn't want to add it to `ko` without having it also work in goreleaser, since there's already some confusing incompatibility between the two, and I'd rather not widen it.

This seems like a real gap though, and doc comments isn't a very solid band-aid 🤔 

Having `ko` gain a flag to override the build config selection could work, but that gets out of hand quickly if you're `ko resolve`ing and building a bunch of things at once.

You could have two binaries, `cmd/puregoapp` and `cmd/cgoapp`, that are just entrypoints for the same codebase, with different `.ko.yaml` configs? That's very gross. 🤮

**Comment by halvards** [comment]
If you're happy to run `ko` from Skaffold (with [native support](https://skaffold.dev/docs/pipeline-stages/builders/ko/), then this config would do:

`.ko.yaml`:
```yaml
defaultBaseImage: gcr.io/distroless/base-debian10
```

`skaffold.yaml`:
```yaml
apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
  - image: ko://example.com/skaffold-profiles
    ko:
      env:
      - CGO_ENABLED=1
profiles:
- name: purego
  build:
    artifacts:
    - image: ko://example.com/skaffold-profiles
      ko:
        flags:
        - -tags=purego
```

To build the default image:

```shell
SKAFFOLD_DEFAULT_REPO=gcr.io/project-id skaffold build
```

To use the `purego` profile:

```shell
SKAFFOLD_DEFAULT_REPO=gcr.io/project-id skaffold build --profile=purego
```
