### ISSUE TITLE
CGO_ENABLED=0 breaks go-sqlite3, Error : Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work

### ISSUE THREAD

**Issue by xmlking** [google/ko#52]
also tried `defaultBaseImage: gcr.io/distroless/base` without any luck

Test : repo to reproduce https://github.com/xmlking/micro-starter-kit

```bash
export KO_DOCKER_REPO=gcr.io/ngx-starter-kit
ko resolve -P -f deploy/ > release.yaml

# run
docker run -it --rm  --env CONFIG_FILE=/var/run/ko/config.yaml  --env APP_ENV=production  -p 8080:8080   gcr.io/ngx-starter-kit/github.com/xmlking/micro-starter-kit/srv/account:latest
```

Error
`
panic: could not build 'user-repository'  because the build function panicked: could not build 'database': Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
`

**Comment by jonjohnsonjr** [comment]
We could tackle this in a couple ways...
<hr>

We could check for `CGO_ENABLED` in the environment, and only set `CGO_ENABLED=0` if it's unset.

This would allow you to build a specific image with:

```
$ export CGO_ENABLED=1
$ ko resolve -P -f deploy/ > release.yaml
```

That would be a simple change [here](https://github.com/google/ko/blob/0c205ab8e4e0de28cb8747bc8ce257d981d095f3/pkg/build/gobuild.go#L120). Unfortunately, this would be global for your invocation of `ko`, so you couldn't enable cgo for an individual image :(
<hr>

Or, we could expand the config file to allow build flags and environment variables to be configured in on a per-package basis.

This is similar to how we allow overriding the base image: https://github.com/google/ko#overriding-the-base-for-particular-imports

Something like this:
```yaml
baseImageOverrides:
  github.com/my-org/my-repo/path/to/binary: docker.io/another/base:latest
buildOverrides:
  github.com/my-org/my-repo/path/to/binary:
    env:
    - name: CGO_ENABLED
      value: 1
    flags:
    - name: ldflags
      value: "-X main.Version=foo"
```

I don't love either of these solutions, but I also don't think it's reasonable for us to just not work with packages that require cgo... also open to other solutions I'm not seeing :)

**Comment by xmlking** [comment]
i think second option is more appropriate way to support   fine graded controle.
eventually we may need to support more customizations for image building. `.ko.yaml` is right  place to store them.

**Comment by xmlking** [comment]
switching the order, let user provide any custom environment  variables or overwrite. with this work ?
 
```go
cmd.Env = append(os.Environ(), "CGO_ENABLED=0", "GOOS=linux")
```
to
```go
cmd.Env = append([]string{"CGO_ENABLED=0", "GOOS=linux"}, os.Environ() )
```

**Comment by jonjohnsonjr** [comment]
That seems reasonable to me

**Comment by xmlking** [comment]
thanks. would you recommend me to set a PR?

**Comment by xmlking** [comment]
eventually we can further support customization for `kodata`
```yaml
baseImageOverrides:
  github.com/my-org/my-repo/path/to/binary: docker.io/another/base:latest
buildOverrides:
  github.com/my-org/my-repo/path/to/binary:
    env:
    - name: CGO_ENABLED
      value: 1
    flags:
    - name: ldflags
      value: "-X main.Version=foo"
    data:
    - source: "config/template"
      destination: "/template"
    - source: "config/seed"
      destination: "/seed"
```
