### ISSUE TITLE
ko hangs when used with ASDF installed Go

### ISSUE THREAD

**Issue by StevenACoffman** [google/ko#530]
I am able to reproduce either a bug, or a misconfiguration that could perhaps use a better error message of some sort.

The reproduction is here at [StevenACoffman/repro](https://github.com/StevenACoffman/repro).

### Repro 

If you clone that repo and run:

```
export GOPRIVATE=github.com/StevenACoffman
cd sub
ko publish -B --bare --local --platform=linux/amd64 --push=false .
```
The terminal will just hang there until you hit Ctrl-c.

At which point, it will then say:
```
^CError: error creating builder: 'builds': entry #0 does not contain a valid local import path (./.) for directory (.): err: signal: interrupt: stderr:
2021/12/12 21:00:19 error during command execution:error creating builder: 'builds': entry #0 does not contain a valid local import path (./.) for directory (.): err: signal: interrupt: stderr:
```

However, if you delete the `.ko.yaml` file in that directory and run it again, things work as you'd expect.
```
rm .ko.yaml
ko publish -B --bare --local --platform=linux/amd64 --push=false .
```

I have tried a number of different possible values for "main" and "dir" and "id" in the `.ko.yaml` file, including omitting them altogether. For instance, setting the `main:` to the values `github.com/StevenACoffman/repro/sub`, `.`, and `main` don't seem to affect this hanging behavior.

[`.ko.yaml`](https://github.com/StevenACoffman/repro/blob/main/sub/.ko.yaml)  contents:
```
# KO_DOCKER_REPO should be either kind.local
# (for KinD) or ko.local

defaultBaseImage: gcr.io/distroless/static
builds:
  # You can have multiple builds defined as a yaml list
  -
    # ID of the build.
    # Defaults to the project name.
    id: "my-build"

    # Path to project's (sub)directory containing Go code.
    # This is the working directory for the Go build command(s).
    # Default is `.`.
    dir: .

    # Path to main.go file or main package.
    # Notice: when used with `gomod.proxy`, this must be a package.
    #
    # Default is `.`.
    main: github.com/StevenACoffman/repro/sub


    ldflags:
      - -s 
      - -w
      - -X main.AppName=Working

    # Custom environment variables to be set during the builds.
    # Default is empty.
    env:
      - CGO_ENABLED=0
``` 

Any help or tips would be greatly appreciated!

**Comment by halvards** [comment]
Thanks for filing

With `ko` v0.9.3, I couldn't reproduce the hanging behavior with the repo you provided:

```shell
$ ko version
0.9.3

$ git clone https://github.com/StevenACoffman/repro.git

$ export GOPRIVATE=github.com/StevenACoffman

$ cd sub

$ ko publish -B --bare --local --platform=linux/amd64 --push=false .
2021/12/13 14:08:08 Using base gcr.io/distroless/static for github.com/StevenACoffman/repro/sub
2021/12/13 14:08:11 Building github.com/StevenACoffman/repro/sub for linux/amd64
2021/12/13 14:08:12 Loading ko.local/sub:445cfe3dd7dcad8f41b8eb35058687973182ee7d7a3d57270c29dc58143d3293
2021/12/13 14:08:12 Loaded ko.local/sub:445cfe3dd7dcad8f41b8eb35058687973182ee7d7a3d57270c29dc58143d3293
2021/12/13 14:08:12 Adding tag latest
2021/12/13 14:08:12 Added tag latest
ko.local/sub:445cfe3dd7dcad8f41b8eb35058687973182ee7d7a3d57270c29dc58143d3293
```

However, the build config from `.ko.yaml` isn't applied, because the `dir`+`main` doesn't match the directory containing `package main`. That's why, when running the image, the output is the following:

```shell
$ docker run --detach --rm --publish 8080:8080 ko.local/sub:445cfe3dd7dcad8f41b8eb35058687973182ee7d7a3d57270c29dc58143d3293

$ curl -s localhost:8080
Hello from unknown, !
```

If I change `main` to `.` and rebuild, this is the result:

```shell
$ curl -s localhost:8080
Hello from Working, !
```

A few points to note:

- The `-B` (`--base-import-paths`) and `--bare` flags are not designed to be used together, and in this case, `-B` takes precedence: https://github.com/google/ko#naming-images

- The `main` field in `.ko.yaml` is a directory, not a full Go import path.

- If your `.ko.yaml` and `go.mod` are in the same directory as your main package, and if this directory is also your working directory, then you can leave out `dir` and `main`.

- `ko` sets `CGO_ENABLED=0` by default.

Based on the above, a simpler version of your `.ko.yaml` would be this:

```yaml
builds:
- id: anything
  ldflags:
  - -s
  - -w
  - -X main.AppName=Working
```

Here's what I got with the simplified `.ko.yaml`:

```shell
$ image=$(ko publish -B --local .)

$ docker run --detach --rm --publish 8080:8080 $image

$ curl -s localhost:8080
Hello from Working, !
```

If you build `ko` from the main branch, the output includes a line that indicates which build config was applied (if any):

```
2021/12/13 14:12:25 Using build config my-build for github.com/StevenACoffman/repro/sub
```

This line is absent if no build config from `.ko.yaml` matched the module.
