### ISSUE TITLE
custom kodataRoot and kodata per image

### ISSUE THREAD

**Issue by xmlking** [google/ko#54]
proposing to support customizing `kodataRoot` per image level. currently it is hardcoded at `/var/run/ko`

```
const kodataRoot = "/var/run/ko"
```

also would be nice to allow developers to keep  `kodata`  in any prefered directory relative to source root.
this allow to keep per module   `kodata`  folder in `monorepo` projects that represent multiple sub modules

**Comment by jonjohnsonjr** [comment]
Somewhat related https://github.com/google/ko/issues/55

**Comment by marekschwarz** [comment]
Can you make a suggestion on how to supply the custom `kodataRoot`?

**Comment by xmlking** [comment]
here is the proposal for copying multiple source directories to image
  
```yaml
baseImageOverrides:
  github.com/my-org/my-repo/path/to/binary: docker.io/another/base:latest
buildOverrides:
  github.com/my-org/my-repo/path/to/binary:
    env:
    - name: CGO_ENABLED
      value: 1
    flags:
    - name: ldflags
      value: "-X main.Version=foo"
    data:
    - source: "config/template"
      destination: "template"
    - source: "config/seed"
      destination: "data/seed"
```

`destination` is relative to `WorkingDir`
`source` is relative to `PrtojectRoot`
