### ISSUE TITLE
allow modifying base image specified in baseImageOverrides section within .ko.yaml

### ISSUE THREAD

**Issue by developer-guy** [google/ko#570]
We thought that it'd be nice if we can add another section to let people specify what packages do they need while running the container image. For example, I need a git executable in order to run my go application properly, but on the other hand side, I want to use distroless base image, so, maybe ko can help us here by giving me a chance to specify what packages do I want to install on my base image, is it worth to implement?

```YAML
defaultBaseImage: registry.example.com/base/image
packages:
  - git 
```

cc: @dentrax @eminaktas @yasintahaerol
