### ISSUE TITLE
Allow setting labels in .ko.yaml

### ISSUE THREAD

**Issue by xmlking** [google/ko#633]
I have multi service **monorepo** where I like to add all my image  `labels` at top level, instead of passing  via `--image-label`  command line options.  

```yaml
defaultBaseImage: gcr.io/distroless/static:nonroot

labels:
  org.opencontainers.image.licenses: MIT
  org.opencontainers.image.source: https://github.com/xmlking/grpc-starter-kit

builds:
  - id: greeter
    dir: .  # default is .
    main: ./service/greeter  # default is .
    ldflags:
      - -s -w
      - -extldflags "-static"
```
